#!/usr/bin/env bash
#
# bootstrap installs things.
#

DOTFILES_ROOT="`pwd`"

# exit if any command exits with nonzero status
set -e

echo ''

# logging functions

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

# sub-functions

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

aditionally () {
  info 'special links'
  python `dirname $0`/link

  # get fonts
  source `dirname $0`/get-powerline-fonts

  info 'install local programs'
  $HOME/.bin/scripts/kermit-install-programs-local

  # scripts location TODO: write a (.gitignored) config file to the scripts/ folder stating this location
  META_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  SCRIPTS_DIR=`dirname $META_DIR`/scripts
  info 'need sudo to write to /etc/kermit-location and install essential programs'
  echo $SCRIPTS_DIR | sudo tee /etc/kermit-location

  # we need the Ubuntu sudo same PATH hack...
  . $HOME/.bin/scripts/kermit-computer-profile
  . $HOME/.bin/scripts/kermit-computer-shrc
  # ...to install essentials TODO: before everything, OS-independent (dotfiles.github.com)
  sudo kermit-install-programs-essential

  # zsh default
  chsh -s $(which zsh)
}

# the main dotfile linking function

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi

  done
}

install_dotfiles
aditionally

echo ''
echo 'All installed!'
