#!/bin/bash

intexit() {
    # Kill all subprocesses (all processes in the current process group)
    kill -HUP -$$
}

hupexit() {
    # HUP'd (probably by intexit)
    echo
    echo "Interrupted. Killing server & guard."
    exit
}

# run a web server
function server() {
    local port="${1:-8000}"

    if hash php 2>/dev/null; then
        nohup php -S 0.0.0.0:"$port" > /dev/null 2>&1 &
    else
        nohup python -m SimpleHTTPServer "$port" > /dev/null 2>&1 &
    fi

    kermit-open "http://localhost:${port}/" > /dev/null 2>&1

    if hash php 2>/dev/null; then
        #nohup guard > /dev/null 2>&1 &
        guard &
    fi

}

trap hupexit HUP
trap intexit INT

server "${1:-8000}"

wait
