#!/bin/bash

# kermit-download-site
USAGE="kermit-download-site <depth> <url> [<wait>]"
if [ -n "$1" ]
# Test whether command-line argument is present (non-empty).
then
  DEPTH=$1
else
  echo $USAGE
  exit
fi

if [ -n "$2" ]
# Test whether command-line argument is present (non-empty).
then
  URL=$2
else
  echo $USAGE
  exit
fi

if [ -n "$3" ]
# Test whether command-line argument is present (non-empty).
then
  WAIT=$3
else
  WAIT=1
fi


wget -mk -np -l $DEPTH --wait=$WAIT $URL


exit
