#!/bin/bash

# kermit-look [dark|light]

# Change iterm2 profile. Usage it2prof ProfileName (case sensitive)
it2prof() {
    echo -e "\033]50;SetProfile=$1\a"
}

if [ -n "$1" ]; then
  mod=$1
else
  echo Must specify name as an argument
  exit
fi

ext_add() {
    pic=${1}.jpg
    if [ -f $pic ]; then
	:
    else
	pic=${1}.png
    fi
    echo $pic
}



if [ $mod == 'dark' ]; then
    bckg=$(ext_add ~/dark)
    iterm2variant=""
else
    mod=light
    bckg=$(ext_add ~/light)
    iterm2variant="Light"
fi

# OS-specific
##################
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Linux
    # desktop background
    echo Setting background to ${bckg}
    gsettings set org.gnome.desktop.background picture-uri file://${bckg}

    # gnome
    cd ~/code/drugi/solarized/gnome-terminal-colors-solarized/
    ./install.sh -s ${mod} -p Default

    # guake
    cd ~/code/drugi/solarized/guake-colors-solarized
    ./set_${mod}.sh

    # emacs
    emacsclient -e "(load-theme 'solarized-${mod} t)"


elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OS X
    it2prof kermit$iterm2variant
    #
    /Applications/Emacs.app/Contents/MacOS/bin/emacsclient -e "(set-background-mode nil '${mod})"
fi


exit
