#!/bin/bash

# install stuff that I use very often

apt-get install -y audacity aptitude build-essential bzr-explorer gimp guake inkscape mypaint ubuntu-restricted-extras vlc vlc-plugin-pulse xclip

add-apt-repository -y ppa:me-davidsansome/clementine-dev

apt-get update

apt-get install -y clementine

exit
