#!/bin/bash

# install only the basic stuff!

apt-get install -y build-essential curl git-core python-pip python-pip3 zsh

# because the Debian package behaves oddly
# http://askubuntu.com/questions/251378/where-is-virtualenvwrapper-sh
pip uninstall virtualenvwrapper # only temporary
pip3 install virtualenvwrapper

# Add PPAs
#---------
# enable adding
if type add-apt-repository > /dev/null 2>&1 ; then
    :
else
    apt-get install python-software-properties
fi

# Emacs24
add-apt-repository -y ppa:cassou/emacs


apt-get update

if dpkg -l ubuntu-desktop > /dev/null 2>&1 ; then
    apt-get install -y emacs-snapshot-gtk
else
    apt-get install -y emacs-snapshot-nox keychain
fi

apt-get install emacs-snapshot-el

exit
