#!/bin/bash

# kermitr-script-edit <sleep time>
if [ -n "$1" ]
# Test whether command-line argument is present (non-empty).
then
  SLEEP_TIME=$1
else  
  echo Must specify sleep time as an argument
  exit
fi

kermit-computer-startup-base $SLEEP_TIME &
#synergyc -f quadrophenia &
sleep $SLEEP_TIME
indicator-cpufreq &
sleep $SLEEP_TIME
synergyc -f quadrophenia &
sleep $SLEPP_TIME
caffeine &
sleep $SLEEP_TIME
conky &

exit
