#!/bin/bash

# install only the basic stuff!

apt-get install -y build-essential curl editorconfig git-core python-pip \
        python3-pip zsh virtualenvwrapper
# some python libraries that take ages to compile
apt-get install -y python-numpy python-scipy python-matplotlib python3-numpy \
    python3-scipy python3-matplotlib

# because the Debian package behaves oddly
# http://askubuntu.com/questions/251378/where-is-virtualenvwrapper-sh
# install an additional virtualenvwrapper for python3
pip3 install virtualenv virtualenvwrapper

# Add PPAs
#---------
# enable adding
if type add-apt-repository > /dev/null 2>&1 ; then
    :
else
    apt-get install python-software-properties
fi

# Emacs24
add-apt-repository -y ppa:cassou/emacs


apt-get update

if dpkg -l ubuntu-desktop > /dev/null 2>&1 ; then
    apt-get install -y emacs-snapshot-gtk
else
    apt-get install -y emacs-snapshot-nox keychain
fi

apt-get install emacs-snapshot-el

exit
