#!/bin/bash

install_sudo() {

apt-get install -y biblatex bsdtar chromium-browser compiz-plugins compizconfig-settings-manager gespeaker git glade gnupg golang goldendict gtk-recordmydesktop libfreetype6-dev mbrola mbrola-cr1 mbrola-us1 mbrola-us2 mbrola-en1 mbrola-de6 mbrola-it3 mbrola-it4 meld miro netcat network-manager-vpnc-gnome nmap openclipart-libreoffice openssh-server p7zip pandoc pbuilder picard pitivi playonlinux pulseaudio-module-jack python-numpy python-matplotlib qtcreator quicksynergy rapidsvn rednotebook shutter synaptic subdownloader tex4ht texlive texlive-math-extra texlive-science texmaker vim wireshark xcalib xchm

#TOFIX cheese

# for selectable TTS
apt-get install -y festival xsel uni2ascii lynx

# PPA-only programs
#------------------
# FFS
add-apt-repository -y ppa:freefilesync/ffs
# Lingo
#apt-add-repository -y ppa:elementary-os/daily
#apt-add-repository -y ppa:nemequ/sqlheavy
# Sublime Text 2
add-apt-repository -y ppa:webupd8team/sublime-text-2
# Polly
add-apt-repository -y ppa:conscioususer/polly-unstable
# Rhythmbox plugins
add-apt-repository -y ppa:fossfreedom/rhythmbox-plugins
# PPA Purge
add-apt-repository -y ppa:nilarimogard/webupd8
# docker
# tmp transition ...
ppa-purge ppa:dotcloud/lxc-docker
#...
apt-get install -y linux-image-extra-`uname -r`
sh -c "curl https://get.docker.io/gpg | apt-key add -"
sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
# ufw setup for docker
sed -i 's/^DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
ufw reload

apt-get update

apt-get install -y freefilesync lxc-docker polly ppa-purge rhythmbox-plugin-llyrics sublime-text

}

# the essentials are in this script...
kermit-install-programs-essential
kermit-install-programs-comfy

install_sudo

# and now for the non-sudo stuff
/usr/bin/sudo -u `logname` env PATH=$PATH kermit-install-programs-local
