#!/bin/bash

# kermitr-script-edit name
if [ -n "$1" ]
# Test whether command-line argument is present (non-empty).
then
  name=$1
else  
  echo Must specify script name as an argument
  exit
fi

. kermit-script-cd
echo Editing script $name at location `pwd`

edtr=emacs

type $edtr >/dev/null 2>&1 || { edtr=vim; echo "fallback vim"; }

#if type $edtr &>/dev/null 2>&1; then edtr=vim; echo "fallback vim"; fi

$edtr $name

exit
