#!/bin/bash

# kermit-script-new
# create a new script

if [ -n "$1" ]
# Test whether command-line argument is present (non-empty).
then
  name=$1
else  
  echo Must specify name as an argument
  exit
fi

. kermit-script-cd

echo Creating script $name at location `pwd`

cp kermit-script-template $name

vim $name

exit
