#!/bin/bash

# kermit's shell rc file

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # http://stackoverflow.com/questions/257616/sudo-changes-path-why
    alias sudo='sudo env PATH=$PATH'
fi


if hash workon 2>/dev/null; then
    workon s
fi

# TODO: figure out how to divide stuff between profile and shrc
#. ~/.bin/scripts/kermit-computer-profile
