#!/bin/bash

install_sudo(){

apt-get install -y audacity aptitude biblatex bsdtar bzr-explorer chromium-browser compiz-plugins compizconfig-settings-manager gespeaker gimp glade gnupg golang goldendict gtk-recordmydesktop guake inkscape libfreetype6-dev lxc mbrola mbrola-cr1 mbrola-us1 mbrola-us2 mbrola-en1 mbrola-de6 mbrola-it3 mbrola-it4 meld miro netcat network-manager-vpnc-gnome nmap openclipart-libreoffice openssh-server p7zip pandoc pbuilder picard pitivi playonlinux pulseaudio-module-jack python-numpy python-matplotlib qtcreator quicksynergy rapidsvn rednotebook shutter synaptic subdownloader tex4ht texlive texlive-math-extra texlive-science texmaker ubuntu-restricted-extras vim vlc vlc-plugin-pulse wireshark xcalib xchm xclip

#TOFIX cheese

# for selectable TTS
apt-get install -y festival xsel uni2ascii lynx

# PPA-only programs
#------------------
# FFS
add-apt-repository -y ppa:freefilesync/ffs
# Lingo
#apt-add-repository -y ppa:elementary-os/daily
#apt-add-repository -y ppa:nemequ/sqlheavy
# Sublime Text 2
add-apt-repository -y ppa:webupd8team/sublime-text-2
# Polly
add-apt-repository -y ppa:conscioususer/polly-unstable
# Rhythmbox plugins
add-apt-repository -y ppa:fossfreedom/rhythmbox-plugins
# docker
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:dotcloud/lxc-docker


apt-get update

apt-get install freefilesync lxc-docker polly rhythmbox-plugin-llyrics sublime-text

}

# the essentials are in this script...
kermit-install-programs-essential

install_sudo

# and now for the non-sudo stuff
sudo -u $SUDO_USER kermit-install-programs-local
