#!/bin/bash

# kermitr-script-edit name
if [ -n "$1" ]
# Test whether command-line argument is present (non-empty).
then
  name=$1
else
  echo Must specify script name as an argument
  exit
fi

echo Editing script $name at location `kermit-script-location`

(. kermit-script-cd; kermit-edit $name)

exit
