#!/bin/bash

# run a web server
function server() {
	local port="${1:-8000}"

	#nohup python -m SimpleHTTPServer "$port" > /dev/null 2>&1 &
	nohup php -S 0.0.0.0:"$port" > /dev/null 2>&1 &
	#nohup guard > /dev/null 2>&1 &
	guard

	kermit-open "http://localhost:${port}/" > /dev/null 2>&1

}

server "${1:-8000}"

exit
